export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_RECIPES_SUCCESS = 'LOAD_RECIPES_SUCCESS';
export const FETCH_RECIPE_SUCCESS = 'FETCH_RECIPE_SUCCESS';
export const FETCH_RECIPE_ERROR = 'FETCH_RECIPE_ERROR';

export const ENABLE_ASSISTANT = 'ENABLE_ASSISTANT';
export const DISABLE_ASSISTANT = 'DISABLE_ASSISTANT';


export const BOT_ANSWER_SUCCESS = 'BOT_ANSWER_SUCCESS';
